// Generated by scripts/gen-fixtures.ts. Edit the generator, never this file.
// The demo account's own identities — see app/data/selectors.ts.
export const USER_ID = "9eec12c3-9503-5550-9a03-1c4f86c3b4fa";
export const PATIENT_ID = "a78f8514-1ee1-54f8-808d-95e3b5a0d8a0";
export const EXPERT_ID = "7fc697c7-1037-5f0d-b3de-3581323538d8";
export const PHARMACY_ID = "a9d23d6e-f056-5692-a5ae-56c5931496b2";
export const LAB_ID = "b8caede4-2ed1-5327-a898-52baa1da7168";
export const STAFF_ID = "b432ce1d-52a5-5261-9b74-9f1dbcbfe549";

// Rows app/data/screen-manifest.ts links to. See SCREEN_LINK_SLUGS.
export const FIXTURE_IDS = {
  app_001: "a9311da8-7ae8-5fee-8a95-e4ee8dce8cce",
  app_002: "3953a6d3-e2f1-5135-899b-2f4617aee2be",
  ccr_001: "28986b1e-78ef-53cc-ba86-146750bf7056",
  chk_006: "1a26868c-03d2-53bf-b48d-f561f302fce7",
  con_002: "6370b9b9-896d-5c66-a2ac-82f3082e6d48",
  con_003: "7ea9a8b9-6c36-53bd-9731-7f42104d4062",
  con_005: "776a9f3a-024a-52c3-96c9-93f704169af6",
  con_007: "a9d5a917-0c72-5a02-a347-2937886f4a43",
  con_009: "01ead9e9-a0d9-5600-b56a-53ceded4f826",
  con_012: "8473065d-8449-593b-85b3-f2bad60aff16",
  con_106: "69200834-2aee-5231-b9db-a67c01a18a20",
  dsp_002: "6b1f0dee-b513-50fc-ae20-7ae776cb2819",
  exp_adisa: "f09bdef0-2281-5f43-945b-e9ff4b184707",
  exp_etim: "e1d4e07f-a4af-5ef1-843d-2f7bf78759a7",
  exp_garba: "616b7528-114e-5c9a-9a0a-bb5acd31f892",
  exp_lawal: "11d39e2d-d793-54af-b774-9cde47bb6018",
  exp_nwosu: "0165234e-9163-5b22-ab77-a6cff5b526a7",
  ins_001: "4bc547ad-62de-58b9-8c2e-8fe936ab6436",
  lab_002: "cc6f005a-ec99-5763-9bff-e5b63f7d363b",
  lab_003: "75fecf43-6256-5233-8e0d-02825caee71d",
  lab_006: "f75b2343-2ab7-5fdb-98c2-89ac38f245f5",
  log_0001: "5b5dac25-8dba-57cd-b0b6-d9329e72aabc",
  pat_amara: "a78f8514-1ee1-54f8-808d-95e3b5a0d8a0",
  pat_zainab: "bed7735f-56ee-58bd-8ffe-b3df58fe8cad",
  po_102: "4e971734-bcba-508d-ab7f-aec67eb7a06b",
  preq_101: "818360fe-860f-587b-9572-3926c734ab99",
  preq_103: "4a60e206-b703-59d4-92bf-142ec07f7328",
  preq_201: "be95719b-6c8e-597c-8e1c-166975b048d0",
  preq_202: "fbd04800-3d8f-51bc-befc-3e6a7e100405",
  prv_lab_pathcare: "b152af64-32c3-5228-b4a6-8ecc3447c1b1",
  prv_ph_greenlife: "a9d23d6e-f056-5692-a5ae-56c5931496b2",
  rep_001: "2f00f38d-4436-5130-ab02-c354e9d8eff4",
  rfd_001: "e5e86915-cbbc-548c-8bf4-048be28f84f2",
  rfd_003: "15ae391f-c1fd-520e-92e7-1371f3c28ace",
  rx_002: "99dc6bc1-aaaa-5a1c-8ee8-c1be638cf332",
  rx_003: "62a57543-75fd-5168-9aab-aa7c8418350b",
  std_001: "092424c0-9b1b-5ca8-b5f1-cd84a614c01b",
} as const;
